/**
 * Karpathy-style wiki: auto-generated, cross-linked prose pages — one per unit,
 * plus an index grouped by architectural layer. Pages narrate what each unit is,
 * how it works, and how it connects, and embed the source. Exportable as
 * markdown you can commit into the repo (like a hand-written wiki, but generated).
 */
import { extname } from "node:path";
import { dependentsOf } from "./analyze.js";
import type { LlmProvider } from "./enrich.js";
import { bandName, computeLayers } from "./layers.js";
import { narrateStep } from "./tours.js";
import type { LearningUnit } from "./units.js";

export interface WikiPage {
  unitId: string;
  slug: string;
  title: string;
  markdown: string;
}

export interface Wiki {
  index: string;
  pages: WikiPage[];
}

const LANG: Record<string, string> = {
  ".py": "python",
  ".js": "javascript",
  ".mjs": "javascript",
  ".cjs": "javascript",
  ".ts": "typescript",
  ".tsx": "tsx",
  ".jsx": "jsx",
};

function slugify(s: string): string {
  return (
    s
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 48) || "unit"
  );
}

function shortHash(s: string): string {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) | 0;
  return (h >>> 0).toString(36).slice(0, 6);
}

export async function generateWiki(opts: {
  units: LearningUnit[]; // in learning-path order
  sourceOf: (u: LearningUnit) => string;
  provider?: LlmProvider;
}): Promise<Wiki> {
  const { units, sourceOf, provider } = opts;
  const { depth, maxDepth } = computeLayers(units);
  const deps = dependentsOf(units);
  const byId = new Map(units.map((u) => [u.id, u]));

  const slugOf = new Map<string, string>();
  for (const u of units) slugOf.set(u.id, `${slugify(u.title)}-${shortHash(u.id)}`);

  const link = (id: string) => {
    const u = byId.get(id);
    return u ? `[${u.title}](./${slugOf.get(id)}.md)` : id;
  };

  const pages: WikiPage[] = [];
  for (const u of units) {
    const buildsOnIds = u.prerequisites.filter((p) => byId.has(p));
    const usedByIds = [...(deps.get(u.id) ?? [])];
    const src = sourceOf(u);
    const narration = await narrateStep(
      u,
      src,
      buildsOnIds.map((id) => byId.get(id)!.title),
      usedByIds.map((id) => byId.get(id)!.title),
      provider,
    );
    const band = bandName(depth.get(u.id) ?? 0, maxDepth);
    const lang = LANG[extname(u.provenance.path).toLowerCase()] ?? "";
    const isCode = Boolean(lang);

    const md = [
      `# ${u.title}`,
      ``,
      `\`${u.provenance.path}:${u.provenance.startLine}-${u.provenance.endLine}\` · **${band}** layer · ${u.kind}`,
      ``,
      narration,
      ``,
      buildsOnIds.length ? `**Builds on:** ${buildsOnIds.map(link).join(" · ")}` : "",
      usedByIds.length ? `**Used by:** ${usedByIds.map(link).join(" · ")}` : "",
      ``,
      isCode ? "## Source" : "## Content",
      ``,
      isCode ? `\`\`\`${lang}` : "",
      src.trimEnd(),
      isCode ? "```" : "",
      ``,
      `— [← back to index](./index.md)`,
      ``,
    ]
      .filter((l) => l !== null)
      .join("\n");

    pages.push({ unitId: u.id, slug: slugOf.get(u.id)!, title: u.title, markdown: md });
  }

  // index grouped by band, foundation first
  const bands = new Map<number, { name: string; lines: string[] }>();
  for (const u of units) {
    const d = depth.get(u.id) ?? 0;
    if (!bands.has(d)) bands.set(d, { name: bandName(d, maxDepth), lines: [] });
    bands.get(d)!.lines.push(`- [${u.title}](./${slugOf.get(u.id)}.md) — \`${u.provenance.path}\``);
  }
  const indexParts = [
    `# Project Wiki`,
    ``,
    `Auto-generated by Master-Anything — ${units.length} units across ${bands.size} architectural layer(s).`,
    ``,
  ];
  for (const d of [...bands.keys()].sort((a, b) => a - b)) {
    const b = bands.get(d)!;
    indexParts.push(`## ${b.name}`, ``, ...b.lines, ``);
  }

  return { index: indexParts.join("\n"), pages };
}

/** Render the wiki as a list of files to write (index.md + one page per unit). */
export function wikiFiles(wiki: Wiki): { path: string; content: string }[] {
  return [
    { path: "index.md", content: wiki.index },
    ...wiki.pages.map((p) => ({ path: `${p.slug}.md`, content: p.markdown })),
  ];
}
